### ISSUE TITLE
ICDrama error, view log

### ISSUE THREAD

**Issue by Achilleus1** [aznhusband/aznhusband.github.io#45] opened 2020-05-31 21:33 UTC
ICDrama have not been working for the past few days. Tried everything, reinstalling, full wipe FireStick , still have the same error.

“2020-05-31 12:54:01.069 T:16512 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.icdrama/?action=Dversions&url=http%3 failed 2020-05-31 12:54:01.055 T:27822 ERROR: GetDirectory - Error getting plugin://plugin.video.icdrama/?action=versions&url=http%3a%2f%2fwww1.adrama.to%2fhk-d -->End of Python script error report<-- Exception: Bad URL: http://www1.adrama.to/hk-drama/6095-the-exorcist-s-2nd-meter/ raise Exception('Bad URL: %s' % url) File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.icdrama/lit 14, in _get out = func(*args, **kargs)”

This is the Logfile error, anyone have a solution?

I’m currently using a FireStick for viewing.

**Comment by jcheong-1** [comment] 2020-05-31 23:02
Duplicate of #43

**Comment by LQQK324** [comment] 2020-05-31 23:16
The website probably changed,  waiting for an update for aznhusband. Give him time he already knows

**Comment by aznhusband** [comment] 2020-06-08 01:37
Closing, #43 is the bug to watch, fixed (hopefully) in 2.1.0

**Closed by aznhusband** 2020-06-08 01:37 UTC
